config/routes.rb
Rails.application.routes.draw do

  resources :planets, only: [:show], param: :name
  resources :users
  resources :account_activations, only: [:edit]
  resources :password_resets, only: [:new, :create, :edit, :update]

  ### GET
  ## Static pages
  # home page
  root 'static_pages#home'
  # contact information
  get '/contact', to: 'static_pages#contact'
  # login from root page
  get '/', to: 'sessions#new'
  # login from login page
  get '/login', to: 'sessions#new'
  # signup
  get '/signup', to: 'users#new'
  # building
  get 'building/upgrade', to: 'buildings#upgrade'
  get 'building/percent', to: 'buildings#percent_bar'

  ### POST
  # signup
  post '/signup', to: 'users#create'
  # building
  post 'building/upgrade', to: 'buildings#upgrade'
  post 'building/cancel', to: 'buildings#cancel_upgrade_building'
  # unit
  post 'unit/train', to: 'units#train'
  # login from root page
  post '/', to: 'sessions#create'
  # login from login page
  post '/login', to: 'sessions#create'

  ### DELETE
  # disconnect
  delete '/logout', to: 'sessions#destroy'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/controllers/buildings_controller.rb
class BuildingsController < ApplicationController
  before_action :logged_in_user, :set_planet, :set_buildings

  # POST /building/upgrade, params[:id]
  # GET /building/upgrade?planet_id=1&position=1
  def upgrade
    # TODO: return proper REST status
    position = params[:position]
    # GET
    if request.get?
      return planet_url(@planet.id) if position.nil?
      @building = Building.where(["planet_id = ? and position = ?", @planet.id, position]).first
      unless @building.nil?
        @building.food_price = @building.next_level.dig(:food_price).to_i
        @building.metal_price = @building.next_level.dig(:metal_price).to_i
        @building.thorium_price = @building.next_level.dig(:thorium_price).to_i
        @building.time_to_build = @building.next_level.dig(:time_to_build).to_i
        @building.production = @building.next_level.dig(:production).to_i ||= 0
        @building.conso_power = @building.next_level.dig(:conso_power).to_i ||= 0
        @buildings = [@building]
      end
      respond_to do |format|
        format.html
        format.json { render json:
          {
            :buildings => @buildings
          }
        }
      end
    end

    # POST
    if request.post?
      flash_message = ""
      status = "warning"
      message_dep = @building.hasDependencies unless @building.nil?

      if @building.nil?
        return unexpected_error(1)
      elsif @building.planet_id != current_user.id
        return redirect_to planet_url(current_user.id)
      elsif message_dep
        flash_message = message_dep
      elsif !@building.upgrade_start.nil?
        flash_message = "Ce bâtiment est déjà en cours d'amélioration"
      elsif !@planet.buildings.select { |b| !b.upgrade_start.nil? }.empty?
        flash_message = "Un bâtiment est déjà en cours d'amélioration."
      elsif !@planet.check_power_availability(@building.next_level.dig(:conso_power).to_i ||= 0)
        flash_message = "Energie insuffisante"
      elsif !@planet.check_ressources_availability(@building.next_level.dig(:thorium_price).to_i, @building.next_level.dig(:metal_price).to_i, @building.next_level.dig(:food_price).to_i)
        flash_message = "Nous manquons de ressources"
      else
        if @building.lvl == 0 && !position.nil?
          @building.set_position(position)
          redirect_to planet_url(@planet)
        end
        @building.upgrading
        @planet = set_planet
        flash_message = "Bâtiment en cours de construction !"
        status = "success"
      end

      respond_to do |format|
        format.js { flash.now[status] = flash_message }
        format.json { render json:
          {
            :building => @building,
            :planet => @planet
          }
        }
      end
    end
  end

  def cancel_upgrade_building
    flash_message = nil
    status = nil
    if @building.nil?
      unexpected_error(2)
    elsif @building.planet_id != current_user.id
      return redirect_to planet_url(current_user.id)
    elsif @building.upgrade_start.nil?
      flash_message = "Le bâtiment n'est pas en amélioration"
      status = "warning"
    else
      flash_message = "L'amélioration du bâtiment est annulée"
      status = "success"
      @building.cancel_upgrading
      @planet = set_planet
    end
    respond_to do |format|
      format.js { flash.now[status] = flash_message }
      format.json { render json:
        {
          :planet => @planet
        }
      }
    end
  end

  def percent_bar
    @percent = compute_remaining_percent(@building)
    @buildings_finished = Building.where(["planet_id = ? and lvl != ?", @planet.id, 0]).order(:id)
    respond_to do |format|
      format.js
      format.json { render json:
        {
          :percent => @percent,
          :building => @building,
          :buildings_finished => @buildings_finished,
          :planet => @planet
        }
      }
    end
  end

  private

  def compute_remaining_percent(b)
    return 0 if b.upgrade_start.nil?
    percent = b.time_remaining * 100 / b.next_level.dig(:time_to_build).to_i
    percent = percent + 100
    percent = 100 if percent > 100
    return percent.nil? ? 0 : percent.abs
  end

  # Confirms a logged-in user.
  def logged_in_user
    unless logged_in?
      store_location
      flash[:danger] = "Veuillez vous connecter pour effectuer cette action."
      redirect_to login_url
    end
  end

  def set_buildings
    @building = Building.find_by(id: params[:id]) unless params[:id].nil?
    @buildings = Building.where(["planet_id = ? and lvl = ? and position is ?", @planet.id, 0, nil]).order(:id).to_a.dup
    @buildings.each do |building|
      @buildings -= [building] if building.hasDependencies
    end
  end

  def set_planet
    @planet = Planet.find(current_user.id) unless current_user.nil?
  end

  def unexpected_error(nb=1)
    flash_message = "Erreur 0x0#{nb}, contactez l'administrateur avec ce code."
    status = "danger"
    respond_to do |format|
      format.js { flash.now[status] = flash_message }
    end
    redirect_to planet_url(@planet)
  end
end

app/helpers/buildings_helper.rb
module BuildingsHelper
  SOLAR_NAME = 'Centrale solaire'.freeze
  SOLAR = [
    { lvl: 1, metal_price: 50, food_price: 25, production: 55, time_to_build: 90 },
    { lvl: 2, metal_price: 75, food_price: 37, production: 108, time_to_build: 171 },
    { lvl: 3, metal_price: 112, food_price: 56, production: 161, time_to_build: 325 },
    { lvl: 4, metal_price: 168, food_price: 84, production: 214, time_to_build: 617 },
    { lvl: 5, metal_price: 253, food_price: 126, production: 267, time_to_build: 1172 },
    { lvl: 6, metal_price: 379, food_price: 189, production: 320, time_to_build: 2228 },
    { lvl: 7, metal_price: 569, food_price: 284, production: 373, time_to_build: 4234 },
    { lvl: 8, metal_price: 854, food_price: 427, production: 426, time_to_build: 8045 },
    { lvl: 9, metal_price: 1281, food_price: 640, production: 479, time_to_build: 15285 },
    { lvl: 10, metal_price: 1922, food_price: 961, production: 532, time_to_build: 29042 },
    { lvl: 11, metal_price: 2883, food_price: 1441, production: 585, time_to_build: 55179 },
    { lvl: 12, metal_price: 4324, food_price: 2162, production: 638, time_to_build: 104841 },
    { lvl: 13, metal_price: 6487, food_price: 3243, production: 691, time_to_build: 199198 }
  ].freeze

  FARM_NAME = 'Champs'.freeze
  FARM = [
    { lvl: 1, food_price: 50, metal_price: 60, conso_power: 22, production: 18, time_to_build: 53 },
    { lvl: 2, food_price: 75, metal_price: 90, conso_power: 46, production: 21, time_to_build: 95 },
    { lvl: 3, food_price: 112, metal_price: 135, conso_power: 70, production: 51, time_to_build: 170 },
    { lvl: 4, food_price: 168, metal_price: 202, conso_power: 94, production: 93, time_to_build: 306 },
    { lvl: 5, food_price: 253, metal_price: 303, conso_power: 118, production: 149, time_to_build: 551 },
    { lvl: 6, food_price: 379, metal_price: 405, conso_power: 142, production: 223, time_to_build: 992 },
    { lvl: 7, food_price: 569, metal_price: 683, conso_power: 166, production: 322, time_to_build: 1785 },
    { lvl: 8, food_price: 854, metal_price: 1025, conso_power: 190, production: 451, time_to_build: 3214 },
    { lvl: 9, food_price: 1281, metal_price: 1537, conso_power: 214, production: 619, time_to_build: 5785 },
    { lvl: 10, food_price: 1922, metal_price: 2306, conso_power: 238, production: 835, time_to_build: 10414 },
    { lvl: 11, food_price: 2883, metal_price: 3459, conso_power: 262, production: 1114, time_to_build: 18745 },
    { lvl: 12, food_price: 4324, metal_price: 5189, conso_power: 286, production: 1471, time_to_build: 33740 },
    { lvl: 13, food_price: 6487, metal_price: 7784, conso_power: 310, production: 1925, time_to_build: 60734 },
    { lvl: 14, food_price: 9730, metal_price: 11677, conso_power: 334, production: 2503, time_to_build: 109320 },
    { lvl: 15, food_price: 14596, metal_price: 17515, conso_power: 358, production: 3235, time_to_build: 196777 },
    { lvl: 16, food_price: 21894, metal_price: 26273, conso_power: 382, production: 4159, time_to_build: 354198 },
    { lvl: 17, food_price: 32842, metal_price: 45978, conso_power: 406, production: 5324, time_to_build: 637557 },
    { lvl: 18, food_price: 49263, metal_price: 68968, conso_power: 430, production: 6788, time_to_build: 1147604 },
    { lvl: 19, food_price: 73894, metal_price: 88673, conso_power: 454, production: 8625, time_to_build: 2065686 },
    { lvl: 20, food_price: 110841, metal_price: 133010, conso_power: 478, production: 10926, time_to_build: 3718235 }
  ].freeze

  METAL_NAME = 'Mine de métaux'.freeze
  METAL = [
      { lvl: 1, food_price: 20, metal_price: 60, conso_power: 11, production: 24, time_to_build: 53 },
      { lvl: 2, food_price: 30, metal_price: 105, conso_power: 46, production: 57, time_to_build: 95 },
      { lvl: 3, food_price: 45, metal_price: 157, conso_power: 70, production: 103, time_to_build: 170 },
      { lvl: 4, food_price: 67, metal_price: 236, conso_power: 94, production: 165, time_to_build: 306 },
      { lvl: 5, food_price: 101, metal_price: 354, conso_power: 118, production: 248, time_to_build: 551 },
      { lvl: 6, food_price: 151, metal_price: 531, conso_power: 142, production: 358, time_to_build: 992 },
      { lvl: 7, food_price: 227, metal_price: 797, conso_power: 16, production: 501, time_to_build: 1785 },
      { lvl: 8, food_price: 341, metal_price: 1196, conso_power: 190, production: 687, time_to_build: 3214 },
      { lvl: 9, food_price: 512, metal_price: 1794, conso_power: 214, production: 928, time_to_build: 5785 },
      { lvl: 10, food_price: 768, metal_price: 2691, conso_power: 238, production: 1238, time_to_build: 10414 },
      { lvl: 11, food_price: 1153, metal_price: 4036, conso_power: 262, production: 1634, time_to_build: 18745 },
      { lvl: 12, food_price: 1729, metal_price: 6054, conso_power: 286, production: 2139, time_to_build: 33740 },
      { lvl: 13, food_price: 2594, metal_price: 9082, conso_power: 310, production: 2781, time_to_build: 60734 },
      { lvl: 14, food_price: 3892, metal_price: 13623, conso_power: 334, production: 3594, time_to_build: 109320 },
      { lvl: 15, food_price: 5838, metal_price: 20435, conso_power: 358, production: 4622, time_to_build: 196777 },
      { lvl: 16, food_price: 8757, metal_price: 30652, conso_power: 382, production: 5916, time_to_build: 354198 },
      { lvl: 17, food_price: 13136, metal_price: 45978, conso_power: 406, production: 7543, time_to_build: 637557 },
      { lvl: 18, food_price: 19705, metal_price: 68968, conso_power: 430, production: 9584, time_to_build: 1147604 },
      { lvl: 19, food_price: 29557, metal_price: 103452, conso_power: 454, production: 12140, time_to_build: 2065686 },
      { lvl: 20, food_price: 44336, metal_price: 155178, conso_power: 478, production: 15355, time_to_build: 3718235 }
  ].freeze

  THORIUM_NAME = 'Mine de thorium'.freeze
  THORIUM = [
    { lvl: 1, metal_price: 50, food_price: 40, conso_power: 22, production: 18, time_to_build: 53 },
    { lvl: 2, metal_price: 75, food_price: 60, conso_power: 46, production: 43, time_to_build: 95 },
    { lvl: 3, metal_price: 112, food_price: 90, conso_power: 70, production: 77, time_to_build: 170 },
    { lvl: 4, metal_price: 168, food_price: 135, conso_power: 94, production: 124, time_to_build: 306 },
    { lvl: 5, metal_price: 253, food_price: 202, conso_power: 118, production: 186, time_to_build: 551 },
    { lvl: 6, metal_price: 379, food_price: 303, conso_power: 142, production: 268, time_to_build: 992 },
    { lvl: 7, metal_price: 569, food_price: 455, conso_power: 166, production: 376, time_to_build: 1785 },
    { lvl: 8, metal_price: 854, food_price: 683, conso_power: 190, production: 515, time_to_build: 3214 },
    { lvl: 9, metal_price: 1281, food_price: 1025, conso_power: 214, production: 696, time_to_build: 5785 },
    { lvl: 10, metal_price: 1922, food_price: 1537, conso_power: 238, production: 928, time_to_build: 10414 },
    { lvl: 11, metal_price: 2883, food_price: 2306, conso_power: 262, production: 1225, time_to_build: 18745 },
    { lvl: 12, metal_price: 4324, food_price: 3459, conso_power: 286, production: 1604, time_to_build: 33740 },
    { lvl: 13, metal_price: 6487, food_price: 5189, conso_power: 310, production: 2086, time_to_build: 60734 },
    { lvl: 14, metal_price: 9730, food_price: 7784, conso_power: 334, production: 2696, time_to_build: 109320 },
    { lvl: 15, metal_price: 14596, food_price: 11677, conso_power: 358, production: 3466, time_to_build: 196777 },
    { lvl: 16, metal_price: 21894, food_price: 17515, conso_power: 382, production: 4437, time_to_build: 354198 },
    { lvl: 17, metal_price: 32842, food_price: 26273, conso_power: 406, production: 5657, time_to_build: 637557 },
    { lvl: 18, metal_price: 49263, food_price: 39410, conso_power: 430, production: 7188, time_to_build: 1147604 },
    { lvl: 19, metal_price: 73894, food_price: 59115, conso_power: 454, production: 9105, time_to_build: 2065686 },
    { lvl: 20, metal_price: 110841, food_price: 88673, conso_power: 478, production: 11501, time_to_build: 3718235 }
  ].freeze

  HEADQUARTER_NAME = 'Centre de commandement'.freeze
  HEADQUARTER = [
    { lvl: 1, metal_price: 600, food_price: 150, thorium_price: 300, time_to_build: 15 },
    { lvl: 2, metal_price: 1260, food_price: 315, thorium_price: 630, time_to_build: 428 },
    { lvl: 3, metal_price: 2646, food_price: 661, thorium_price: 1323, time_to_build: 812 },
    { lvl: 4, metal_price: 5556, food_price: 1389, thorium_price: 2778, time_to_build: 1543 },
    { lvl: 5, metal_price: 11668, food_price: 2917, thorium_price: 5834, time_to_build: 2932 },
    { lvl: 6, metal_price: 24504, food_price: 6126, thorium_price: 12252, time_to_build: 5571 },
    { lvl: 7, metal_price: 51549, food_price: 12864, thorium_price: 25729, time_to_build: 10585 },
    { lvl: 8, metal_price: 108865, food_price: 27016, thorium_price: 54032, time_to_build: 20112 },
    { lvl: 9, metal_price: 226937, food_price: 56734, thorium_price: 113468, time_to_build: 38213 },
    { lvl: 10, metal_price: 476568, food_price: 119142, thorium_price: 238284, time_to_build: 72605 },
    { lvl: 11, metal_price: 1000792, food_price: 250168, thorium_price: 500396, time_to_build: 137948 },
    { lvl: 12, metal_price: 2101665, food_price: 525416, thorium_price: 1050832, time_to_build: 262103 },
    { lvl: 13, metal_price: 4413496, food_price: 1103374, thorium_price: 2206748, time_to_build: 434276 }
  ].freeze

  TRAIN_CAMP_NAME = "Camp d'entrainement".freeze
  TRAIN_CAMP = [
      { lvl: 1, metal_price: 250, food_price: 250, thorium_price: 100, time_to_build: 45 },
      { lvl: 2, metal_price: 500, food_price: 500, thorium_price: 128, time_to_build: 86 },
      { lvl: 3, metal_price: 1000, food_price: 1000, thorium_price: 400, time_to_build: 162 },
      { lvl: 4, metal_price: 1344, food_price: 1344, thorium_price: 800, time_to_build: 308 },
      { lvl: 5, metal_price: 2688, food_price: 4000, thorium_price: 1024, time_to_build: 1114 },

app/views/buildings/_grid_view.html.erb
<h3>Mes bâtiments</h3>
<% @buildings_finished.each do |building| %>

<div class="tooltips">
    <%= link_to image_tag("buildings/".concat(building.image_name).concat(".jpg"), alt: building.name, :class => "building_image_mini"), building_upgrade_path(position: building.position) %>
    <div class="tooltiptext">
        <span><%= building.name + ' niveau ' + building.lvl.to_s %></span><br />
        <span>Nourriture : <%= building.next_level.dig(:food_price).to_s %></span><br />
        <span>Metal : <%= building.next_level.dig(:metal_price).to_s %></span><br />
        <span>Thorium : <%= building.next_level.dig(:thorium_price).to_s %></span><br />
        <span>Prod. : <%= (building.next_level.dig(:production) || 0).to_s %></span><br />
        <span>Conso. : <%= (building.next_level.dig(:conso_power) || 0) .to_s %></span><br />
        <span>Temps : <%= building.next_level.dig(:time_to_build).to_s %></span>
    </div>
</div>
<% end %>

app/views/buildings/_upgrading.html.erb
<% @buildings.each do |building| %>
<div id="building_<%= building.id %>">
  <div class="building_name">
    <%= building.name %> niveau <%= building.lvl %><br />
  </div>

  <div id="upgrading_infos" class="row">
    <div id="cancel_<%= building.id %>">
      <div id="cancel_btn_<%= building.id %>" class="col-md-6 cancel_btn"">
      <%= button_to "Annuler #{building.name}",
        building_cancel_path(id: building.id),
        method: :post,
        class: 'upgrade_building_button btn btn-light col-md-6',
        remote: true
      %>
      </div>
      <div class="col-md-6">
        <span id="building_finish_at_<%= building.id %>">
          <%= building.finish_at %>
        </span>
        <div id="progress_bar_<%= building.id %>" class="col-md-6">
          <progress id="build_progress_<%= building.id %>" max="100" value="0"> 0% </progress>
        </div>
      </div>
    </div>

  </div>
</div>

<script type="text/javascript">
  // update progress at start
  <% unless building.upgrade_start.nil? %>
    refreshProgress_<%= building.id %>();
    schedule_<%= building.id %>();
  <% else %>
    clearInterval(interval_<%= building.id %>);
  <% end %>
  var interval_<%= building.id %>;
  // call refreshProgress every 3 seconds
  function schedule_<%= building.id %>() {
      interval_<%= building.id %> = setInterval(refreshProgress_<%= building.id %>, 3000);
  }
  // get the percentage
  function refreshProgress_<%= building.id %>() {
      $.ajax({
          url: "<%= building_percent_path(id: building.id) %>"
      })
  }
</script>
<% end %>

app/views/buildings/cancel_upgrade_building.js.erb
<% unless @building.nil? %>
$("#flash_<%= @building.id %>").html('<%= j render partial: "shared/flash_messages" %>');
clearInterval(interval_<%= @building.id %>);
<% end %>
$("#action_building").html('');
$("#canvas").html("<%= j (render partial: 'planets/canvas', :locals => {:planet => @planet}) %>")
$('#resources').html("<%= j (render partial: 'planets/resources', :locals => {:planet => @planet}) %>")
$('#aside_resources').html("<%= j (render partial: 'planets/production', :locals => {:planet => @planet}) %>")

app/views/buildings/new.html.erb
<div class="container">
    <div class="row">
        <%= raw(render('planets/resources')) %>
    </div>
    <div class="row">
        <div id="aside_resources" class="col-md-2">
            <%= raw(render('planets/production')) %>
        </div>
        <div class="col-md-10">
            <%= raw(render('buildings/building_detail')) %>
        </div>
    </div>
</div>

app/views/buildings/percent_bar.js.erb
// get upgrade percentage progress
$("#build_progress_<%= @building.id %>").val("<%= @percent %>");
<% if @building.upgrade_start.nil? %>
// trigger when upgrade_start is finished
// reload building infos
clearInterval(interval_<%= @building.id %>);
$("#action_building").html('');
$("#building_list").html('<%= j render partial: "buildings/upgrading", :locals => {:buildings => @buildings = [@building]} %>');
$(".building_grid_view").html('<%= j render partial: "buildings/grid_view", :locals => {:buildings_finished => @buildings_finished} %>');
// update resources
$('#resources').html("<%= j (render partial: 'planets/resources', :locals => {:planet => @planet}) %>")
$('#aside_resources').html("<%= j (render partial: 'planets/production', :locals => {:planet => @planet}) %>")
if(<%= @building.name == "Camp d'entrainement" %>) {
    $('.units_show').html("<%= j (render partial: 'units/show', :locals => {:planet => @planet}) %>")
}
<% end %>

app/views/buildings/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @building.name %>
</p>

<p>
  <strong>Planet:</strong>
  <%= @building.planet_id %>
</p>

<p>
  <strong>Lvl:</strong>
  <%= @building.lvl %>
</p>

<p>
  <strong>Conso power:</strong>
  <%= @building.conso_power %>
</p>

<p>
  <strong>Time to build:</strong>
  <%= @building.next_level.dig(:time_to_build).to_i %>
</p>

<p>
  <strong>Production:</strong>
  <%= @building.production %>
</p>
<%= link_to 'Back', buildings_path %>

app/views/buildings/upgrade.html.erb
<div class="container">
    <%= raw(render('planets/resources')) %>
    <div class="row">
        <div class="col-md-2">
            <%= raw(render('planets/production')) %>
        </div>
        <div id="building_list" class="col-md-10">
            <% @buildings.each do |building| %>
                <div id="building_<%= building.id %>">
                <div class="building_name">
                    <%= building.name %> niveau <%= building.lvl %><br />
                </div>

                <div id="flash_<%= building.id %>" class="flash_messages">
                    <%= render partial: "shared/flash_messages" %>
                </div>

                <div id="building_description_<%= building.id %>">
                    <%= image_tag("buildings/".concat(building.image_name).concat(".jpg"), alt: building.name, :id => "img_" + building.image_name, :class => "building_image") %>
                    <ul class="ressources_infos">
                    <li>
                    Nourriture : <%= building.next_level.dig(:food_price).to_i %> -
                    Metal : <%= building.next_level.dig(:metal_price).to_i %> -
                    Thorium : <%= building.next_level.dig(:thorium_price).to_i %>
                    </li>
                    <li>
                    Production : <%= building.next_level.dig(:production).to_i ||= 0 %> -
                    Conso. électricité : <%= building.next_level.dig(:conso_power).to_i ||= 0 %>
                    </li>
                    <li>
                    Temps de construction : <%= building.next_level.dig(:time_to_build).to_i %> secondes
                    </li>
                    </ul>

                </div>

                <div class="row">

                    <div id="upgrade_btn_<%= building.id %>" class="col-md-9 upgrade_btn">
                    <%= button_to building.lvl == 0 ? "Construire #{building.name}" : "Améliorer #{building.name}",
                        building_upgrade_path(id: building.id, position: building.position.nil? ? params[:position] : building.position),
                        method: :post,
                        class: 'upgrade_building_button btn btn-light col-md-6',
                        remote: true
                    %>
                    </div>

                </div>
            </div>
            <% end %>
        </div>
    </div>
</div>

app/views/buildings/upgrade.js.erb
$('#resources').html("<%= j (render partial: 'planets/resources', :locals => {:planet => @planet}) %>")
$('#aside_resources').html("<%= j (render partial: 'planets/production', :locals => {:planet => @planet}) %>")
<% unless @building.nil? %>
$("#flash_<%= @building.id %>").html('<%= j render partial: "shared/flash_messages" %>');
// start recurrent ajax calls
$(function() { schedule_<%= @building.id %>(); });
<% end %>

app/views/buildings/upgrade_building.js.erb
$("#flash").html('<%= j render partial: "shared/flash_messages" %>');
$('#resources').html("<%= j (render partial: 'planets/resources', :locals => {:planet => @planet}) %>")
$('#aside_resources').html("<%= j (render partial: 'planets/production', :locals => {:planet => @planet}) %>")
<% unless @building.nil? %>
// start recurrent ajax calls
$(function() { schedule_<%= @building.id %>(); });
<% end %>