config/routes.rb
Rails.application.routes.draw do

  resources :planets, only: [:show], param: :name
  resources :users
  resources :account_activations, only: [:edit]
  resources :password_resets, only: [:new, :create, :edit, :update]

  ### GET
  ## Static pages
  # home page
  root 'static_pages#home'
  # contact information
  get '/contact', to: 'static_pages#contact'
  # login from root page
  get '/', to: 'sessions#new'
  # login from login page
  get '/login', to: 'sessions#new'
  # signup
  get '/signup', to: 'users#new'
  # building
  get 'building/upgrade', to: 'buildings#upgrade'
  get 'building/percent', to: 'buildings#percent_bar'

  ### POST
  # signup
  post '/signup', to: 'users#create'
  # building
  post 'building/upgrade', to: 'buildings#upgrade'
  post 'building/cancel', to: 'buildings#cancel_upgrade_building'
  # unit
  post 'unit/train', to: 'units#train'
  # login from root page
  post '/', to: 'sessions#create'
  # login from login page
  post '/login', to: 'sessions#create'

  ### DELETE
  # disconnect
  delete '/logout', to: 'sessions#destroy'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/unit.rb
require 'sidekiq/api'

class Unit < ApplicationRecord
  belongs_to :planet
  validates :planet_id, presence: true

  def image_name
    self.name.downcase.tr(" ", "_").tr("ô", "o").tr("é", "e").tr("è", "e").tr("'", "_")
  end

  def isTrainable
    t_lvl = self.planet.train_camp.lvl
    planet_units = self.planet.units.sort

    if t_lvl == 0 || (t_lvl > 0 && planet_units[0] != self) ||
      (t_lvl > 2 && !planet_units[..1].include?(self)) ||
      (t_lvl > 4 && !planet_units[4].include?(self)) ||
      (t_lvl > 5 && ![planet_units[2], planet_units[5]].include?(self)) ||
      (t_lvl > 8 && !planet_units[5..].include?(self))
      return false
    end
    true
  end

  def training(nb_unit)
    # TODO: enclose with try catch
    nb_unit.times { |i|
      unit_t2b = self.time_to_build * i + 1
      puts "--- Unit " + self.id.to_s + " " + self.name + " in queue unit for " + unit_t2b.to_s + "s ---"
      BuildingUpgradeWorker.perform_in(Time.now+unit_t2b, self.id)
    }
    planet.substract_resources_to_total(self)
  end

  def train
    nb = self.number + 1
    self.update(number: nb)
  end
end

app/controllers/units_controller.rb
class UnitsController < ApplicationController
  before_action :set_planet, :set_unit

  def train
    if request.post? && @unit
      # check if unit is owned (403)
      return head(:forbidden) unless @planet.units.map(&:id).include? params[:id].to_i
      flash_message = ""
      status = "warning"

      param_nb_unit = "nb_unit_" + @unit.id.to_s
      nb_unit = check_nb_unit(params[param_nb_unit.to_sym].to_i)
      # check if queue is full
      # check if possible to build
      if !@unit.isTrainable
        flash_message = "Améliorez d'abord le centre d'entrainement !"
      # check if resources
      elsif !@planet.check_ressources_availability(
        @unit.thorium_price.to_i * nb_unit,
        @unit.metal_price.to_i * nb_unit,
        @unit.food_price.to_i * nb_unit
      )
        flash_message = "Nous manquons de ressources"
      else
        @unit.training(nb_unit)
        flash_message = "Unité(s) en cours de construction !"
        status = "success"
      end

      respond_to do |format|
        format.js { flash.now[status] = flash_message }
        format.json { render json:
          {
            :unit => @unit,
            :planet => @planet
          }
        }
      end
    end
  end

  private

    def set_unit
      @unit = Unit.find(params[:id]) unless params[:id].nil?
    end

    def set_planet
      @planet = Planet.find(current_user.id) unless current_user.nil?
    end

    def check_nb_unit(nb_unit)
      # TODO: check training and military lvl
      if nb_unit > 15
        return 15
      elsif nb_unit < 1
        return 1
      else
        return nb_unit
      end
    end
end

app/helpers/units_helper.rb
module UnitsHelper
    LIGHT_INFANTRY = {name: "Infanterie légère", health: 10, attack: 40, defense: 20, intellect: 20, capacity: 100, food_price: 200, metal_price: 400, thorium_price: 0, time_to_build: 450}
    HEAVY_INFANTRY = {name: "Infanterie lourde", health: 30, attack: 80, defense: 50, intellect: 15, capacity: 200, food_price: 200, metal_price: 1200, thorium_price: 300, time_to_build: 600}
    SCIENTIST = {name: "Scientifique", health: 10, attack: 10, defense: 10, intellect: 50, capacity: 75, food_price: 250, metal_price: 800, thorium_price: 150, time_to_build: 750}
    ARCHAEOLOGIST = {name: "Archéologue", health: 10, attack: 15, defense: 10, intellect: 30, capacity: 75, food_price: 150, metal_price: 600, thorium_price: 100, time_to_build: 700}
    SPOT = {name: "Spot", health: 10, attack: 0, defense: 10, intellect: 10, capacity: 1000, food_price: 500, metal_price: 1000, thorium_price: 0, time_to_build: 750}
    DRONE = {name: "Drone", health: 10, attack: 0, defense: 10, intellect: 10, capacity: 0, food_price: 500, metal_price: 1000, thorium_price: 0, time_to_build: 900}
    ATLAS = {name: "Atlas", health: 50, attack: 100, defense: 80, intellect: 10, capacity: 500, food_price: 500, metal_price: 1500, thorium_price: 800, time_to_build: 1000}
    CLONE = {name: "Clone", health: 60, attack: 120, defense: 50, intellect: 40, capacity: 400, food_price: 1000, metal_price: 1000, thorium_price: 1000, time_to_build: 1250}
    SUPER_SOLDIER = {name: "Super soldat", health: 70, attack: 200, defense: 80, intellect: 10, capacity: 200, food_price: 1000, metal_price: 1300, thorium_price: 1500, time_to_build: 1500}
end

app/views/units/_show.html.erb
<h3>Unités</h3>
<% @planet.units.order(:id).each do |unit| %>
  <% if unit.isTrainable %>
  <div id="flash_<%= unit.id %>" class="flash_messages">
    <%= render partial: "shared/flash_messages" %>
  </div>
  <%= image_tag("units/".concat(unit.image_name).concat(".png"), alt: unit.name, :id => "img_" + unit.image_name, :class => "unit_image") %>
  <%= unit.name %>
  <div id="unit_description_<%= unit.id %>" class="row">
    <ul class="ressources_infos">
      <li>
      Nourriture : <%= unit.food_price %> -
      Metal : <%= unit.metal_price %> -
      Thorium : <%= unit.thorium_price %>
      </li>
      <li>
      Santé : <%= unit.health %> -
      Attaque : <%= unit.attack %> -
      Défense : <%= unit.defense %> -
      Capacité : <%= unit.capacity %>
      </li>
      <li>
      Temps de construction : <%= unit.time_to_build %> secondes
      </li>
    </ul>
  </div>
  <div class="row">
    <%= form_with(url: unit_train_path(id: unit.id), remote: true) do |f| %>
      <%= f.number_field :"nb_unit_#{unit.id}", class: 'col-md-2 unit_number', onchange:"max_bound(#{unit.id})", in: 1..15, value: 1 %>
      <input id="max_unit_<%= unit.id %>" class="btn col-md-offset-1 col-md-2" type="button" value="Max" onclick="max_unit(<%= unit.id %>)">
      <%= f.submit "Créer #{unit.name}", class: "btn btn-light col-md-offset-1 col-md-6" %>
    <% end %>
  </div>
  <% end %>
<% end %>

<script type="text/javascript">
  function max_unit(id) {
    input_field_name = "nb_unit_" + id;
    document.getElementById(input_field_name).value = 15;
  }

  function max_bound(id) {
    input_field_name = "nb_unit_" + id;
    input_field = document.getElementById(input_field_name);
    if(input_field.value > input_field.max) {
      input_field.value = input_field.max;
    } else if (input_field.value < input_field.min) {
      input_field.value = input_field.min;
    }
  }
</script>

app/views/units/train.js.erb
$('#resources').html("<%= j (render partial: 'planets/resources', :locals => {:planet => @planet}) %>")
$('#aside_resources').html("<%= j (render partial: 'planets/production', :locals => {:planet => @planet}) %>")
<% unless @unit.nil? %>
$("#flash_<%= @unit.id %>").html('<%= j render partial: "shared/flash_messages" %>');
<% end %>