config/routes.rb
Rails.application.routes.draw do

  resources :planets, only: [:show], param: :name
  resources :users
  resources :account_activations, only: [:edit]
  resources :password_resets, only: [:new, :create, :edit, :update]

  ### GET
  ## Static pages
  # home page
  root 'static_pages#home'
  # contact information
  get '/contact', to: 'static_pages#contact'
  # login from root page
  get '/', to: 'sessions#new'
  # login from login page
  get '/login', to: 'sessions#new'
  # signup
  get '/signup', to: 'users#new'
  # building
  get 'building/upgrade', to: 'buildings#upgrade'
  get 'building/percent', to: 'buildings#percent_bar'

  ### POST
  # signup
  post '/signup', to: 'users#create'
  # building
  post 'building/upgrade', to: 'buildings#upgrade'
  post 'building/cancel', to: 'buildings#cancel_upgrade_building'
  # unit
  post 'unit/train', to: 'units#train'
  # login from root page
  post '/', to: 'sessions#create'
  # login from login page
  post '/login', to: 'sessions#create'

  ### DELETE
  # disconnect
  delete '/logout', to: 'sessions#destroy'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/layouts/_footer.html.erb
<footer>
	<div class="container">
		<div class="row">
			<div class="col-md-10">
				<%= Time.now.year %> - CC BY-NC-ND
			</div>
			<div class="col-md-2">
				<%= link_to "Forum", "https://worldofstars.forumactif.com/" %>
				<%= link_to image_tag("icons/Discord-Logo-Color.png", alt: "Discord", id: "logo-discord", class: "icons"), "https://discord.gg/fPzBJ6VWMt" %>
				<%= link_to image_tag("icons/GitHub-Mark-Light-64px.png", alt: "GitHub", id: "logo-github", class: "icons"), "https://github.com/acouprie/worldofstars" %>
			</div>
		</div>
	</div>
</footer>

app/views/layouts/_header.html.erb
<header>
	<div class="container">
		<div id="banner"><%= link_to image_tag("banner.jpg", 
			alt: "World of Stars banniere", style: "width: 100%;"), root_path %>
		</div>

		<nav>
			<ul class="navbar navbar-inverse nav nav-justified">
				<li class="nav-item"><%= link_to "Accueil", root_path, class: "nav-link" %></li>
				<li class="nav-item"><%= link_to "Forum", 'https://worldofstars.forumactif.com/', class: "nav-link" %></li>
				
				<% if logged_in? %>
					<li class="nav-item"><%= link_to "Ma planète", current_user.planets.first, class: "nav-link" %></li>
					<li class="nav-item"><%= link_to "Classement", users_path, class: "nav-link" %></li>
					<li class="nav-item"><%= link_to "Profil", current_user, class: "nav-link" %></li>
					<li class="nav-item"><%= link_to "Contact", contact_path, class: "nav-link" %></li>
					<li class="nav-item"><%= link_to "Compte", edit_user_path(current_user), class: "nav-link" %></li>
					<li class="nav-item"><%= link_to "Déconnection", logout_path, method: "delete", class: "nav-link" %></li>
				<% else %>
					<li class="nav-item"><%= link_to "Connection", login_path, class: "nav-link" %></li>
					<li class="nav-item"><%= link_to "S'enregistrer", signup_path, class: "nav-link" %></li>
					<li class="nav-item"><%= link_to "Mot de passe oublié", new_password_reset_path, class: "nav-link" %></li>
					<li class="nav-item"><%= link_to "Contact", contact_path, class: "nav-link" %></li>
				<% end %>
			</ul>
		</nav>
		
	</div>
</header>

app/views/layouts/application.html.erb
<% provide(:title, " | World of Stars") %>
<!DOCTYPE html>
<html>
	<head>
		<meta http-equiv = "Content-type" content = "text/html; charset = utf-8">
		<meta keyword = "World of Stars, World of Stargate">
		<title ><%= yield(:title) %></title>
		<%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
		<%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
	</head>
	<body>
		<%= render 'layouts/header' %>

		<div id="notice">
			<%= raw(render('shared/flash_messages')) %>
		</div>

		<%= yield %>

		<%= render 'layouts/footer' %>
	</body>
</html>